server:
  port: 18080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_db:5432/
    username: postgres
    password: aa123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲链接
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 500
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 18000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      allow-pool-suspension: false
      leak-detection-threshold: 5000
      connection-test-query: SELECT 1

flow:
  url: http://flask_service:5000

mybatis-plus:
  type-handlers-package: com.zhd.handler